"""
Reads the historical call-volume xlsx and writes a seed SQL file that
populates `public.call_volume_baseline`.

Rules:
  * Source sheet: "Data" (one row per call).
  * Customer "COPART, INC" is a batch-dispatched bulk customer whose calls
    cluster at 8 AM but whose work occupies the full daytime. We redistribute
    those calls evenly across COPART_WINDOW (8 AM-4 PM inclusive = 9 hours).
  * For each (day_of_week, hour) we emit:
      - one aggregate row (month IS NULL)
      - twelve per-month rows (month = 1..12), where the bucket has data.

Run:
    python scripts/build_call_volume_seed.py

Output:
    supabase/seed/call_volume_baseline_seed.sql
        -> paste into Supabase SQL editor after the migration has run.
"""
from __future__ import annotations
import warnings, os, sys
from collections import defaultdict
warnings.filterwarnings('ignore')
import openpyxl

XLSX_PATH = r'C:\Users\PatricioParraRamon\OneDrive - netruckcenter.com\Desktop\Average Call Per Hour Distribution.xlsx'
OUT_PATH  = os.path.join(os.path.dirname(__file__), '..', 'supabase', 'seed', 'call_volume_baseline_seed.sql')

COPART_NAME      = 'COPART, INC'
COPART_WINDOW    = list(range(8, 17))   # 8,9,10,11,12,13,14,15,16  (9 hours)
SOURCE_TAG       = 'historical_2025'

def main():
    wb = openpyxl.load_workbook(XLSX_PATH, data_only=True, read_only=True)
    sheet = wb['Data']

    # Per-bucket counts. Bucket key shapes:
    #   ('agg', dow, hour)               -> non-Copart count
    #   ('agg_copart', dow)              -> Copart-only count for that dow
    #   ('mon', dow, hour, month)        -> non-Copart count
    #   ('mon_copart', dow, month)       -> Copart count
    counts = defaultdict(int)

    # Unique-day denominators (so we get avg PER OCCURRENCE of that weekday).
    days_seen_agg = defaultdict(set)        # dow      -> set of dates
    days_seen_mon = defaultdict(set)        # (dow,m)  -> set of dates

    rows = 0
    for i, row in enumerate(sheet.iter_rows(values_only=True)):
        if i == 0:
            continue
        if not row or row[0] is None:
            continue
        customer = (row[0] or '').strip()
        date     = row[4]
        hour     = row[8]
        if date is None or hour is None:
            continue
        try:
            hour = int(hour)
            dow  = date.weekday()           # 0=Mon..6=Sun
            month = date.month
        except Exception:
            continue
        if hour < 0 or hour > 23:
            continue

        is_copart = customer.upper() == COPART_NAME

        days_seen_agg[dow].add(date.date() if hasattr(date, 'date') else date)
        days_seen_mon[(dow, month)].add(date.date() if hasattr(date, 'date') else date)

        if is_copart:
            counts[('agg_copart', dow)]            += 1
            counts[('mon_copart', dow, month)]     += 1
        else:
            counts[('agg', dow, hour)]             += 1
            counts[('mon', dow, hour, month)]      += 1

        rows += 1

    print(f'  rows scanned: {rows}', file=sys.stderr)
    print(f'  unique days per dow: {[len(days_seen_agg[d]) for d in range(7)]}', file=sys.stderr)

    # Build the output rows.
    out_rows = []                                       # list of (dow, hour, month_or_None, avg)

    # ----- Aggregate (month IS NULL) -----
    for dow in range(7):
        n_days = len(days_seen_agg[dow])
        if n_days == 0:
            continue
        # Copart redistribution per business hour, per occurrence of this weekday.
        copart_total = counts.get(('agg_copart', dow), 0)
        copart_per_hour_per_day = (copart_total / len(COPART_WINDOW)) / n_days

        for hour in range(24):
            non_copart = counts.get(('agg', dow, hour), 0)
            base = non_copart / n_days
            extra = copart_per_hour_per_day if hour in COPART_WINDOW else 0.0
            out_rows.append((dow, hour, None, base + extra))

    # ----- Per-month -----
    for (dow, month), dates in days_seen_mon.items():
        n_days = len(dates)
        if n_days == 0:
            continue
        copart_total = counts.get(('mon_copart', dow, month), 0)
        copart_per_hour_per_day = (copart_total / len(COPART_WINDOW)) / n_days

        for hour in range(24):
            non_copart = counts.get(('mon', dow, hour, month), 0)
            base = non_copart / n_days
            extra = copart_per_hour_per_day if hour in COPART_WINDOW else 0.0
            out_rows.append((dow, hour, month, base + extra))

    # ----- Emit SQL -----
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        f.write('-- Generated by scripts/build_call_volume_seed.py — do not edit by hand.\n')
        f.write(f'-- Source: {os.path.basename(XLSX_PATH)}\n')
        f.write(f'-- Copart redistribution: even across hours {COPART_WINDOW[0]}-{COPART_WINDOW[-1]} (count={len(COPART_WINDOW)}h).\n\n')
        f.write('BEGIN;\n\n')
        f.write(f"DELETE FROM public.call_volume_baseline WHERE source = '{SOURCE_TAG}';\n\n")
        f.write('INSERT INTO public.call_volume_baseline (day_of_week, hour, month, avg_calls, source) VALUES\n')

        formatted = []
        for dow, hour, month, avg in out_rows:
            m = 'NULL' if month is None else str(month)
            formatted.append(f"  ({dow}, {hour}, {m}, {avg:.3f}, '{SOURCE_TAG}')")
        f.write(',\n'.join(formatted))
        f.write(';\n\nCOMMIT;\n')

    print(f'wrote {len(out_rows)} rows -> {OUT_PATH}')

if __name__ == '__main__':
    main()
